version: '3.6'
services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
    volumes:
      - ./data/db:/var/lib/postgresql/data